config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emprendimiento.urls'))
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emprendimiento/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError
import imghdr
from django.contrib.auth.forms import UserCreationForm


class EmprendimientoForm(forms.ModelForm):
    class Meta:
        model = Emprendimiento
        fields = ['nombre_emprendimiento', 'email_emprendimiento', 
                  'telefono_emprendimiento', 'descripcion_emprendimiento', 
                  'ubicacion_emprendimiento', 'img_emprendimiento']
    
        widgets = {
            'usuario_emprendedor': forms.HiddenInput(),
        }

    def clean_img_emprendimiento(self):
        img_emprendimiento = self.cleaned_data.get('img_emprendimiento')
        if img_emprendimiento:
            # Verifica la extensión del archivo
            ext = img_emprendimiento.name.split('.')[-1].lower()
            if ext not in ['jpg', 'jpeg', 'png']:
                raise ValidationError("Solo se permiten archivos JPG y PNG.")
            # Verifica el tipo MIME del archivo
            if imghdr.what(img_emprendimiento) not in ['jpeg', 'png']:
                raise ValidationError("El archivo no es una imagen válido (JPEG o PNG).")
        return img_emprendimiento

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo_producto', 'nombre_producto', 'descripcion_producto',
                   'precio_producto', 'stock_producto', 'img_producto']
    

class SupportForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['nombre', 'apellido', 'correo', 'mensaje']


class LoginForm(forms.Form):
  username = forms.CharField()
  password = forms.CharField(widget = forms.PasswordInput)


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(label='Nombre', widget=forms.TextInput(attrs={'autocomplete': 'given-name'}))
    last_name = forms.CharField(label='Apellido', widget=forms.TextInput(attrs={'autocomplete': 'family-name'}))
    username = forms.CharField(label='Nombre y apellido', widget=forms.TextInput(attrs={'autocomplete': 'username'}))
    phonenumber = forms.CharField(label='Teléfono', widget=forms.TextInput(attrs={'autocomplete': 'tel'}))
    email = forms.EmailField(label='Correo electrónico', widget=forms.EmailInput(attrs={'autocomplete': 'email'}))
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}))
    password2 = forms.CharField(label='Repita contraseña', widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}))


    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'phonenumber', 'email', 'password1', 'password2')


#para mi cuenta
from .models import UserProfile
from django.contrib.auth.models import User

class UpdateUserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phonenumber']

    def __init__(self, *args, **kwargs):
        super(UpdateUserProfileForm, self).__init__(*args, **kwargs)

        if self.instance.user:
            self.fields['phonenumber'].initial = self.instance.get_phonenumber()

        # Agrega los campos faltantes al formulario
        self.fields['user_first_name'] = forms.CharField(initial=self.instance.user.first_name, required=False)
        self.fields['user_last_name'] = forms.CharField(initial=self.instance.user.last_name, required=False)
        self.fields['user_username'] = forms.CharField(initial=self.instance.user.username, required=False)
        self.fields['user_email'] = forms.EmailField(initial=self.instance.user.email, required=False)

    def save(self, commit=True):
        # Actualiza los datos del usuario antes de guardar el formulario
        if self.instance.user:
            self.instance.user.first_name = self.cleaned_data['user_first_name']
            self.instance.user.last_name = self.cleaned_data['user_last_name']
            self.instance.user.username = self.cleaned_data['user_username']
            self.instance.user.email = self.cleaned_data['user_email']
            self.instance.user.save()

        return super(UpdateUserProfileForm, self).save(commit)

class MiCuentaProductoForm(forms.ModelForm):
    emprendimiento = forms.ModelChoiceField(queryset=Emprendimiento.objects.none(), empty_label=None)
    id_emprendimiento = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Producto
        fields = ['codigo_producto', 'nombre_producto', 'descripcion_producto', 'precio_producto', 'stock_producto', 'img_producto']

    def __init__(self, *args, **kwargs):
        emprendimientos = kwargs.pop('emprendimientos', None)
        super().__init__(*args, **kwargs)
        if emprendimientos is not None:
            self.fields['emprendimiento'].queryset = emprendimientos

config/templates/base_mi_cuenta.html
{% extends 'base.html' %}

{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/base_mi_cuenta.css' %}">
{% endblock %}


{% block panel_lateral %}


<nav class="navbar navbar-expand-lg bg-light justify-content-center" id="base_mi_cuenta">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/datos_usuario">Datos usuario</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/mis_emprendimientos">Mis emprendimientos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/create">Crear emprendimiento</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/mis_productos">Mis productos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/mi_cuenta_create_prod">Crear producto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/cerrar_sesion">Cerrar sesión</a>
                </li>
                <li class="nav-item">
                    <form class="d-flex" id="eliminar-cuenta-form" method="post" action="{% url 'eliminar_cuenta' %}">
                        {% csrf_token %}
                        <a role="button" class="nav-link" onclick="confirmarEliminacion()">Eliminar
                            cuenta</a>
                        <input type="hidden" name="confirmar_eliminar" value="True">
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>





<!--   <div id="baseMicuenta">
        <ul class="miCuenta">
            <li><a href="/datos_usuario">Datos usuario</a></li>
            <li><a href="/mis_emprendimientos">Mis emprendimientos</a></li>
            <li><a href="/create">Crear emprendimiento</a></li>
            <li><a href="/mis_productos">Mis productos</a></li>
            <li><a href="/mi_cuenta_create_prod">Crear producto</a></li>
            <li><a href="#">Mis compras</a></li>
            <li><a href="/cerrar_sesion">Cerrar sesión</a></li>
        </ul>

    </div>
    <form id="eliminar-cuenta-form" method="post" action="{% url 'eliminar_cuenta' %}">
        {% csrf_token %}
        <button class="buttonEliminacion" type="button" onclick="confirmarEliminacion()">Eliminar cuenta</button>
        <input type="hidden" name="confirmar_eliminar" value="True">
    </form>
    -->




<script>
    function confirmarEliminacion() {
        var confirmacion = confirm('¿Estás seguro de eliminar tu cuenta?\nEsta acción eliminará todos tus emprendimientos y productos asociados, si los hay');

        if (confirmacion) {
            document.getElementById('eliminar-cuenta-form').submit();
        }
    }
</script>

{% endblock %}

{% block content %}
{% endblock %}

config/templates/create_ent.html
{% extends 'base_mi_cuenta.html' %}


{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/create_ent.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/base_mi_cuenta.css' %}">

{% endblock %}




{% block content %}


<div class="div_create_ent">

    <h1>Regístrate</h1>
    <p>{{ usuario_emprendedor }}</p>
    <p>Tu emprendimiento</p>

</div>


    <form method="post" enctype="multipart/form-data"
        action="{% url 'create_ent' %}" id="form_create_ent">
        {% csrf_token %}

        <article id="informacion">
            <div class="titulos">
                <label for="{{ formulario.nombre_emprendimiento.id_for_label }}"><b>Nombre de tu
                        emprendimiento*:</b></label>
                {{ formulario.nombre_emprendimiento }}
            </div>

            <div class="titulos">
                <label for="{{ formulario.email_emprendimiento.id_for_label }}"><b>Email de tu
                        emprendimiento*:</b></label>
                {{ formulario.email_emprendimiento }}
            </div>

            <div class="titulos">
                <label for="{{ formulario.telefono_emprendimiento.id_for_label }}"><b>Teléfono*:</b></label>
                {{ formulario.telefono_emprendimiento }}
            </div>

            <div class="titulos">
                <label for="{{ formulario.descripcion_emprendimiento.id_for_label }}"><b>Descripción del
                        emprendimiento*:</b></label>
                {{ formulario.descripcion_emprendimiento }}
            </div>

            <div class="titulos">
                <label for="{{ formulario.ubicacion_emprendimiento.id_for_label }}"><b>Ubicacion*:</b></label>
                {{ formulario.ubicacion_emprendimiento }}
            </div>
        </article>

        <article id="imagenlogo">
            <div class="div_create_ent">
                <label for="{{ formulario.img_emprendimiento.id_for_label }}"><b>Seleccionar logo</b></label>
            {{ formulario.img_emprendimiento }}
            </div>
            <div>
                <div id="vista-previa"></div>
            </div>

            <button type="submit" class="btn">Guardar</button>

        </article>

            
    


    </form>


<br><br><br>



{% endblock %}

config/templates/create_prod.html
{% extends 'base_mi_cuenta.html' %}

{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/create_prod.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/base_mi_cuenta.css' %}">

{% endblock %}

{% block content %}

<main id="encabezado_prod">
    <h1>Regístrate</h1>
    <h2>{{ nombre_emprendedor }}</h2>
    <p>{{ nombre_emprendimiento }}</p>

</main>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <section id="sectiondatos">
        <div class="Nombre_prod">
            <label for="{{ formulario.nombre_producto.id_for_label }}"><b>Nombre del producto*:</b></label>
            {{ formulario.nombre_producto }}
        </div>

        <div class="cod_prod">
            <label for="{{ formulario.codigo_producto.id_for_label }}"><b>Código del Producto*:</b></label>
            {{ formulario.codigo_producto }}
        </div>

        <div class="descr_prod">
            <label for="{{ formulario.descripcion_producto.id_for_label }}"><b>Descripción del
                    Producto*:</b></label>
            {{ formulario.descripcion_producto }}
        </div>

        <div class="Precios">
            <label for="{{ formulario.precio_producto.id_for_label }}"><b>Precio Producto ($)*:</b></label>
            {{ formulario.precio_producto }}
        </div>

        <div class="Stock">
            <label for="{{ formulario.stock_producto.id_for_label }}"><b>Stock de Producto*:</b></label>
            {{ formulario.stock_producto }}
        </div>


    </section>

    <section>
        <h3>
            <p>Agregar un producto</p>
        </h3>

        <div class="img_prod">
            {{ formulario.img_producto }}
        </div>

        <article id="boton">

            <button id="boton11" type="submit" class="btn" name="action" value="guardar-y-agregar">
                <b>Guardar y agregar otro</b>
            </button>

            <button type="submit" class="btn" name="action" value="finalizar">
                <b>Finalizar</b>
            </button>

        </article>
    </section>

</form>


<div class="position-fixed top-0 end-0 p-3" style="z-index: 5">
    {% if messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}:</strong> {{ message }}<br>
        {% endfor %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
</div>

<!-- encargado Ruy, puedes editar acá. Esto se hace con un form -->

{% endblock %}

config/templates/datos_usuario.html
{% extends 'base_mi_cuenta.html' %}


{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/datos_usuario.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/base_mi_cuenta.css' %}">

{% endblock %}



{% block content %}
<div class="container3">
    <div class="row justify-content-center">
        <div class="col-md-6 text-center align-items-center">
            <form method="post" action="{% url 'datos_usuario' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_user_first_name" class="form-label">Nombre de usuario*:</label>
                    <input type="text" class="form-control" id="id_user_first_name" name="user_first_name"
                        value="{{ form.instance.user.first_name }}">
                </div>

                <div class="mb-3">
                    <label for="id_user_last_name" class="form-label">Apellido*:</label>
                    <input type="text" class="form-control" id="id_user_last_name" name="user_last_name"
                        value="{{ form.instance.user.last_name }}">
                </div>

                <div class="mb-3">
                    <label for="id_user_username" class="form-label">Usuario*:</label>
                    <input type="text" class="form-control" id="id_user_username" name="user_username"
                        value="{{ form.instance.user.username }}">
                </div>

                <div class="mb-3">
                    <label for="id_phonenumber" class="form-label">Teléfono*:</label>
                    <input type="text" class="form-control" id="id_phonenumber" name="phonenumber"
                        value="{{ form.instance.phonenumber }}">

                </div>
                <div class="mb-3">
                    <label for="id_user_email" class="form-label">Email*:</label>
                    <input type="email" class="form-control" id="id_user_email" name="user_email"
                        value="{{ form.instance.user.email }}">
                </div>


                <button type="submit" class="support-submit-button"
                    id="support-submit-button"><b>Actualizar</b></button>

            </form>
        </div>
    </div>
</div>

<div class="position-fixed top-0 end-0 p-3" style="z-index: 5">
    {% if messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}:</strong> {{ message }}<br>
        {% endfor %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
</div>


<!--<form method="post" action="{% url 'datos_usuario' %}">
    {% csrf_token %}
    <article>
        <div class="parte1">
            <div>
                <label for="id_user_first_name"><b>Nombre*:</b></label>
                <input type="text" id="id_user_first_name" name="user_first_name" value="{{ form.instance.user.first_name }}">
            </div>
            <div>
                <label for="id_user_last_name"><b>Apellido*:</b></label>
                <input type="text" id="id_user_last_name" name="user_last_name" value="{{ form.instance.user.last_name }}">
            </div>
        </div>

        <div class="segundaparte">
            <div>
                <label for="id_user_username"><b>Usuario*:</b></label>
                <input type="text" id="id_user_username" name="user_username" value="{{ form.instance.user.username }}">
            </div>
            <div>
                <label for="id_phonenumber"><b>Teléfono*:</b></label>
                <input type="text" id="id_phonenumber" name="phonenumber" value="{{ form.instance.phonenumber }}">
            </div>
        </div>

        <div class="descripcion">
            <label for="id_user_email"><b>Email*:</b></label>
            <input type="text" id="id_user_email" name="user_email" value="{{ form.instance.user.email }}">
        </div>

        <button class="buttonDatos" type="submit">Actualizar</button>
    </article>
</form>
-->


{% endblock %}

config/templates/delete_prod.html
{% extends 'base_mi_cuenta.html' %}

{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/delete_prod.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/base_mi_cuenta.css' %}">

{% endblock %}



{% block content %}

<main id="main_delete_ent">

    <div id="delete_ent">


        <div class="contenedor">
            <h1 id="h1_delete_ent">Hola</h1>
            <h2 id="h2_delete_ent">{{ nombre_emprendedor }}</h2>
            <h2 id="h3_delete_ent">{{ nombre_emprendimiento }}</h2>


        </div>

        <div>
            <ul class="contenedor">
                <li>Mis productos</li>
                <li>Producto: {{ nombre_producto }}</li>
                <li>Código: {{ codigo_producto }}</li>
            </ul>
        </div>


        <div class="eliminar">
            <p>Eliminar producto</p>
        </div>
        <form method="post">
            {% csrf_token %}
            
            <div class="codigo">
                <h2>¿Estás seguro de eliminar este producto?</h2>
                <h2>{{ codigo_producto }}: {{ nombre_producto }}</h2>
                {% if producto.img_producto %}
                <img src="{{ producto.img_producto.url }}" alt="{{ product.nombre_producto }}" id="logo_ent">
                {% else %}
                No hay imagen disponible
                {% endif %}
            </div>

            <div class="d-grid gap-2" id="delete_ent">
                <button class="btn btn-primary" type="submit">Confirmar</button>
            </div>
        </form>

    </div>





</main>



{% endblock %}

config/templates/detail_ent.html
{% extends 'base.html' %}


{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/detail_ent.css' %}">
{% endblock %}


{% block content %}


<nav class="container">
    {% if emprendimiento.img_emprendimiento %}
    <img src="{{ emprendimiento.img_emprendimiento.url }}" class="logo"
        alt="{{ emprendimiento.nombre_emprendimiento }}">
    {% endif %}
    <h1>{{ emprendimiento.nombre_emprendimiento }}</h1>
</nav>

<ul class="container">
    <li>Descripción: {{ emprendimiento.descripcion_emprendimiento }}</li>
    <li>Ubicación: {{ emprendimiento.ubicacion_emprendimiento }}</li>
</ul>

<div class="row">
    {% for producto in productos %}
    <div class="col-lg-4 mb-4">
        <div class="card">
            {% if producto.img_producto %}
            <img src="{{ producto.img_producto.url }}" class="card-img-top" alt="{{ producto.nombre_producto }}">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">Producto: {{ producto.nombre_producto }}</h5>
                <p class="card-text">Código: {{ producto.codigo_producto }}</p>
                <p class="card-text">Descripción: {{ producto.descripcion_producto }}</p>
                <p class="card-text">Precio: {{ producto.precio_producto }} $</p>
                <p class="card-text">Stock: {{ producto.stock_producto }} unidades</p>
                {% if user.is_authenticated %}
                <a href="{% url 'agregar_al_carrito' producto_id=producto.id_producto %}" class="btn btn-agregar" role="button">Agregar al
                    carrito</a>
                {% else %}
                <a href="{% url 'compra_productos' %}" class="btn btn-agregar" role="button">Agregar
                    al carrito</a>
                {% endif %}
                </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="position-fixed top-0 end-0 p-3" style="z-index: 5">
    {% if messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {% for message in messages %}
                <strong>{{ message.tags }}:</strong> {{ message }}<br>
            {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
</div>


{% endblock %}

config/templates/list_prod.html
{% extends 'base.html' %}

{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/list_prod.css' %}">
{% endblock %}



{% block content %}

<div class="principal">
    <!-- encargada Yilda, puedes editar acá -->
    {% for e in products %}
    <div class="container">
        {% if e.img_producto %}
        <image src="{{ e.img_producto.url }}" alt="{{ e.nombre_producto }}" class="img_prod">
            {% else %}
            No hay imagen disponible
            {% endif %}
            <h1>Producto: {{ e.nombre_producto }}</h1>
            <div>
                <p><b>Vendido por: {{ e.id_emprendimiento.nombre_emprendimiento }}</b></p>
            </div>
            <div>
                <p><b>Precio: {{ e.precio_producto }} $</b></p>
            </div>
            <div>
                <p><b>Stock: {{ e.stock_producto }}</b></p>
            </div>

            {% if request.alert_messages %}
            <div class="alert alert-info" role="alert">
                {% for message in request.alert_messages %}
                {{ message }}<br>
                {% endfor %}
            </div>
            {% endif %}


            {% if user.is_authenticated %}
            <a href="{% url 'agregar_al_carrito' producto_id=e.id_producto %}" class="btn btn-agregar" role="button">Agregar al
                carrito</a>
            {% else %}
            <a href="{% url 'compra_productos' %}" class="btn btn-agregar" role="button">Agregar
                al carrito</a>
            {% endif %}
    </div>
    {% endfor %}

    <div class="position-fixed top-0 end-0 p-3" style="z-index: 5">
        {% if messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {% for message in messages %}
                    <strong>{{ message.tags }}:</strong> {{ message }}<br>
                {% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
    </div>
    


</div>


{% endblock %}

config/templates/mi_cuenta_create_prod.html
{% extends 'base_mi_cuenta.html' %}

{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/mi_cuenta_create_prod.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/base_mi_cuenta.css' %}">

{% endblock %}


{% block content %}

<form class="carol" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <section id="sectiondatos">
        <div class="Nombre_prod">
            <label for="{{ formulario.nombre_producto.id_for_label }}"><b>Nombre del producto*:</b></label>
            {{ formulario.nombre_producto }}
        </div>

        <div class="cod_prod">
            <label for="{{ formulario.codigo_producto.id_for_label }}"><b>Código del Producto*:</b></label>
            {{ formulario.codigo_producto }}
        </div>

        <div class="descr_prod">
            <label for="{{ formulario.descripcion_producto.id_for_label }}"><b>Descripción del
                    Producto*:</b></label>
            {{ formulario.descripcion_producto }}
        </div>

        <div class="Precios">
            <label for="{{ formulario.precio_producto.id_for_label }}"><b>Precio Producto ($)*:</b></label>
            {{ formulario.precio_producto }}
        </div>

        <div class="Stock">
            <label for="{{ formulario.stock_producto.id_for_label }}"><b>Stock de Producto*:</b></label>
            {{ formulario.stock_producto }}
        </div>

        <div class="Stock">
            <label for="{{ formulario.emprendimiento.id_for_label }}">Emprendimiento:</label>
            {{ formulario.emprendimiento }}
        </div>

    </section>

    <section>
        <h3 class="h3agregarproducto">Agregar Producto</h3>

        <div class="img_prod">
            {{ formulario.img_producto }}
        </div>

        <div style="display: none;">
            {{ formulario.id_emprendimiento }}
        </div>

        <article id="botonproducto">
            <button type="submit" class="botonproducto" name="action" value="guardar-y-agregar">
                <b>Guardar y agregar otro</b>
            </button>
            <button type="submit" class="botonproducto" name="action" value="finalizar">
                <b>Finalizar</b>
            </button>
        </article>
    </section>

</form>
</header>


<div class="position-fixed top-0 end-0 p-3" style="z-index: 5">
    {% if messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}:</strong> {{ message }}<br>
        {% endfor %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
</div>



{% endblock %}

config/templates/mi_cuenta_det_emprend.html
{% extends 'base_mi_cuenta.html' %}

{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/mi_cuenta_det_emprend.css' %}">
{% endblock %}

{% block content %}


<nav class="container">
    {% if emprendimiento.img_emprendimiento %}
    <img src="{{ emprendimiento.img_emprendimiento.url }}" class="logo"
        alt="{{ emprendimiento.nombre_emprendimiento }}">
    {% endif %}
    <h1>{{ emprendimiento.nombre_emprendimiento }}</h1>
</nav>

<ul class="container">
    <li>Descripción: {{ emprendimiento.descripcion_emprendimiento }}</li>
    <li>Ubicación: {{ emprendimiento.ubicacion_emprendimiento }}</li>
</ul>

<div class="row">
    {% for producto in productos %}
    <div class="col-lg-4 mb-4">
        <div class="card">
            {% if producto.img_producto %}
            <img src="{{ producto.img_producto.url }}" class="card-img-top" alt="{{ producto.nombre_producto }}">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">Producto: {{ producto.nombre_producto }}</h5>
                <p class="card-text">Código: {{ producto.codigo_producto }}</p>
                <p class="card-text">Descripción: {{ producto.descripcion_producto }}</p>
                <p class="card-text">Precio: {{ producto.precio_producto }} $</p>
                <p class="card-text">Stock: {{ producto.stock_producto }} unidades</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>



{% endblock %}